include <../Gearbox/variables.scad>

$fa = 1;
$fs = 0.1;

STAGES = 3;

// Holder bolt connector and bolt shell
HOLDER_BOLT_CONNECTOR_AMOUNT = 2*BOLT_NUMBER;
HOLDER_BOLT_CONNECTOR_REAL_DIAMETER = BOLT_HEAD_DIAMETER+2*BOLT_WALL_WIDTH;
HOLDER_BOLT_CONNECTOR_DIAMETER_TOLERANCE = 2*0.5;
HOLDER_BOLT_CONNECTOR_DIAMETER = HOLDER_BOLT_CONNECTOR_REAL_DIAMETER+HOLDER_BOLT_CONNECTOR_DIAMETER_TOLERANCE;
HOLDER_BOLT_CONNECTOR_OFFSET = BOLT_OFFSET+HOLDER_BOLT_CONNECTOR_DIAMETER/2;

HOLDER_BOLT_SHELL_INNER_DIAMETER = RING_GEAR_CASE_DIAMETER+2*0.4;
HOLDER_BOLT_SHELL_MIN_WALL_THICKNESS = 1.5;
HOLDER_BOLT_SHELL_OUTER_DIAMETER = 2*(HOLDER_BOLT_CONNECTOR_OFFSET+HOLDER_BOLT_CONNECTOR_DIAMETER/2)+2*HOLDER_BOLT_SHELL_MIN_WALL_THICKNESS;
HOLDER_BOLT_SHELL_HEIGHT = 74.8+3;

// Holder motor shell
HOLDER_MOTOR_SHELL_WALL_THICKNESS = HOLDER_BOLT_SHELL_MIN_WALL_THICKNESS;
HOLDER_MOTOR_SHELL_HEIGHT = 66.5;
HOLDER_MOTOR_SHELL_PLATE_BEARING_HOLE_DIAMETER = 15+2*1.5;
HOLDER_MOTOR_SHELL_PLATE_BEARING_HEIGHT = 10+2;
HOLDER_MOTOR_SHELL_PLATE_BEARING_COVER_HEIGHT = 2;
HOLDER_MOTOR_SHELL_PLATE_HEIGHT = HOLDER_MOTOR_SHELL_PLATE_BEARING_HEIGHT+HOLDER_MOTOR_SHELL_PLATE_BEARING_COVER_HEIGHT;
HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_WIDTH = 3.8;
HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_WIDTH_TOLERANCE = 2*1.5;
HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_HEIGHT = 7.7+2*1.5;
HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_OFFSET = 15.7+(HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_WIDTH/2); // Offset to center of hole.
HOLDER_MOTOR_SHELL_TOTAL_HEIGHT = HOLDER_MOTOR_SHELL_PLATE_HEIGHT+HOLDER_MOTOR_SHELL_HEIGHT;

// Holder top cover
HOLDER_TOP_COVER_HEIGHT = 2;

// Holder wall mount
HOLDER_WALL_MOUNT_SCREW_TIGHT_DIAMETER = 6+2*0.2;
HOLDER_WALL_MOUNT_SCREW_PASSAGE_DIAMETER = 12+2*0.4;
HOLDER_WALL_MOUNT_SCREW_PASSAGE_HEIGHT = 4.4+0.4;
HOLDER_WALL_MOUNT_HEIGHT = HOLDER_WALL_MOUNT_SCREW_PASSAGE_DIAMETER+2*2; // Applies per side, not for both sides together.
HOLDER_WALL_MOUNT_DEPTH = 15+HOLDER_WALL_MOUNT_SCREW_PASSAGE_HEIGHT;

echo("Holder wall mount height ", HOLDER_WALL_MOUNT_HEIGHT);
echo("Motor center distance from wall ", HOLDER_BOLT_SHELL_OUTER_DIAMETER/2);

module holder_bolt_connector() {
	difference() {
		union() {
			// Shell bolt outer cylinder
			color("lightgreen")
				cylinder(d=HOLDER_BOLT_SHELL_OUTER_DIAMETER, h=HOLDER_BOLT_SHELL_HEIGHT);
		}
		
		// Shell inner cylinder
		translate([0, 0, -0.01])
			cylinder(d=HOLDER_BOLT_SHELL_INNER_DIAMETER, h=HOLDER_BOLT_SHELL_HEIGHT+0.02);
			
		// Mounts
		for(i=[0:HOLDER_BOLT_CONNECTOR_AMOUNT-1]) {
			rotate([0, 0, (360/HOLDER_BOLT_CONNECTOR_AMOUNT)*i])
			translate([HOLDER_BOLT_CONNECTOR_OFFSET, 0, -0.01])
				cylinder(d=HOLDER_BOLT_CONNECTOR_DIAMETER, h=HOLDER_BOLT_SHELL_HEIGHT+0.02);
		}
	}
}

module holder_motor_shell() {
	// Plate
	difference() {
		cylinder(d=HOLDER_BOLT_SHELL_OUTER_DIAMETER, h=HOLDER_MOTOR_SHELL_PLATE_HEIGHT);
		
		// Plate bearing hole
		translate([0, 0, -0.01])
			cylinder(d=HOLDER_MOTOR_SHELL_PLATE_BEARING_HOLE_DIAMETER, h=HOLDER_MOTOR_SHELL_PLATE_HEIGHT+0.02);
			
		// Plate Power Holes
		power_hole_real_width = HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_WIDTH+HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_WIDTH_TOLERANCE;
		for(i=[0:1]) {
			rotate([0, 0, i*180])
			translate([-power_hole_real_width/2+HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_OFFSET, -HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_HEIGHT/2, -0.01])
				cube([power_hole_real_width, HOLDER_MOTOR_SHELL_PLATE_POWER_HOLES_HEIGHT, HOLDER_MOTOR_SHELL_PLATE_HEIGHT+0.02]);
		}
	}
	
	cylinder(d=HOLDER_MOTOR_SHELL_PLATE_BEARING_HOLE_DIAMETER+2*0.01, h=HOLDER_MOTOR_SHELL_PLATE_BEARING_COVER_HEIGHT);
	
	// Shell
	translate([0, 0, HOLDER_MOTOR_SHELL_PLATE_HEIGHT]) {
		difference() {
			cylinder(d=HOLDER_BOLT_SHELL_OUTER_DIAMETER, h=HOLDER_MOTOR_SHELL_HEIGHT);
			translate([0, 0, -0.01])
				cylinder(d=HOLDER_BOLT_SHELL_OUTER_DIAMETER-2*HOLDER_MOTOR_SHELL_WALL_THICKNESS, h=HOLDER_MOTOR_SHELL_HEIGHT+0.02);
		}
	}
}

module holder_top_cover() {
	difference() {
		cylinder(d=HOLDER_BOLT_SHELL_OUTER_DIAMETER, h=HOLDER_TOP_COVER_HEIGHT);
		
		translate([0, 0, -0.01])
			cylinder(d=TOP_COVER_HOLE_DIAMETER, h=HOLDER_TOP_COVER_HEIGHT+0.02);
	}
}

module holder_wall_mount() {
	total_height = HOLDER_MOTOR_SHELL_TOTAL_HEIGHT+HOLDER_BOLT_SHELL_HEIGHT;
	
	difference() {
		translate([0, 0, 0.01])
		union() {
			translate([-HOLDER_BOLT_SHELL_OUTER_DIAMETER/2, 0, 0])
				cube([HOLDER_BOLT_SHELL_OUTER_DIAMETER, HOLDER_BOLT_SHELL_OUTER_DIAMETER/2, total_height-0.02]);

			// Screw plate
			total_plane_width = HOLDER_BOLT_SHELL_OUTER_DIAMETER+2*HOLDER_WALL_MOUNT_HEIGHT;
			translate([-total_plane_width/2, HOLDER_BOLT_SHELL_OUTER_DIAMETER/2-HOLDER_WALL_MOUNT_DEPTH, 0])
				cube([total_plane_width, HOLDER_WALL_MOUNT_DEPTH, total_height-0.02]);
		}
			
		cylinder(d=HOLDER_BOLT_SHELL_OUTER_DIAMETER, h=total_height);
	
		// Screw holes
		for(i=[0:1]) {
			translate([(i == 0 ? -1 : 1)*(HOLDER_BOLT_SHELL_OUTER_DIAMETER/2+HOLDER_WALL_MOUNT_HEIGHT/2), 0, total_height/2]) {
				translate([0, HOLDER_BOLT_SHELL_OUTER_DIAMETER/2-HOLDER_WALL_MOUNT_DEPTH+HOLDER_WALL_MOUNT_SCREW_PASSAGE_HEIGHT, 0])
				rotate([90, 0, 0])
					cylinder(d=HOLDER_WALL_MOUNT_SCREW_PASSAGE_DIAMETER, h=HOLDER_WALL_MOUNT_SCREW_PASSAGE_HEIGHT+0.01);
					
				translate([0, HOLDER_BOLT_SHELL_OUTER_DIAMETER/2+0.01, 0])
				rotate([90, 0, 0])
					cylinder(d=HOLDER_WALL_MOUNT_SCREW_TIGHT_DIAMETER, h=HOLDER_WALL_MOUNT_DEPTH-HOLDER_WALL_MOUNT_SCREW_PASSAGE_HEIGHT+0.02);
			}
		}
	}
}

module gearbox_holder() {
	holder_motor_shell();
	
	translate([0, 0, HOLDER_MOTOR_SHELL_TOTAL_HEIGHT])
		holder_bolt_connector();
	
	color("yellow")
		holder_wall_mount();
	
	// Print top cover seperately and glue it onto the body. 
	// color("orange")
	// translate([0, 0, HOLDER_MOTOR_SHELL_TOTAL_HEIGHT+HOLDER_BOLT_SHELL_HEIGHT])
	// 	holder_top_cover();
}