esphome:
  name: blinds-1
  includes:
    - BlindsMotorSwitch.h

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "We?W9%N6]ZeP9?EEb9scY#Rsy3U3}eu36?)J/MJ2xroD4/N"

ota:
  password: "We?W9%N6]ZeP9?EEb9scY#Rsy3U3}eu36?)J/MJ2xroD4/N"

wifi:
  ssid: "kruitzer"
  password: "Hu88l3Bu88l3"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Blinds-1 Fallback Hotspot"
    password: "YELWNULX0vvn"

captive_portal:    

switch:
  - platform: gpio
    pin: 4
    name: "Motor Switch Relay 1"
    id: relay_1
    
  - platform: gpio
    pin: 0
    name: "Motor Switch Relay 2"
    id: relay_2

  - platform: gpio
    pin: 5
    name: "Motor Switch 2"

globals:
      - id: blinds_are_opened
        type: bool
        restore_value: no
        initial_value: 'true'  

cover:
    - platform: template
      name: Léon Bedroom Blinds
      id: cover_blinds
      device_class: garage
      lambda: |-
        if (id(blinds_are_opened) == true) {
          return COVER_OPEN;
        } else {
          return COVER_CLOSED;
        }
      
      open_action:
        - switch.turn_on: relay_2
        - switch.turn_on: relay_1
        - delay: 68s
        - switch.turn_off: relay_1
        - globals.set:
            id: blinds_are_opened
            value: 'true'
        
      close_action:
        - switch.turn_off: relay_1
        - switch.turn_off: relay_2
        - delay: 56s
        - switch.turn_on: relay_2
        - globals.set:
            id: blinds_are_opened
            value: 'false'

  # - platform: custom
  #   lambda: |-
  #     auto blindsMotorSwitch = new BlindsMotorSwitch();
  #     App.register_component(blindsMotorSwitch);
  #     return { blindsMotorSwitch };
  #   switches:
  #     - name: "Motor Switch"
